on:
  push:
    branches: master
    paths:
      - README.Rmd

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    default:
      shell: Rscript {0}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown and remotes
        run: install.packages(c("rmarkdown", "remotes"))
      - name: Install package
        run: remotes::install_local(".")
      - name: Render README
        run: rmarkdown::render("README.Rmd")
      - name: Commit results
        run: |
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin
        shell: bash
